### ISSUE TITLE
不能运行在server render的框架下 

### ISSUE THREAD

**Issue by LeafInStrom** [yi/node-chinese-browser-agent#1]
[1] [piping] error given was: ReferenceError: window is not defined
[1]     at Object.<anonymous> (/node_modules/chinese-browser-agent/lib/index.js:21:9)

**Comment by yi** [comment]
sorry its not designed for outside-browser

2016年7月3日星期日，LeafInStrom notifications@github.com 写道：

> [1] [piping] error given was: ReferenceError: window is not defined
> [1] at Object. (/node_modules/chinese-browser-agent/lib/index.js:21:9)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/yi/node-chinese-browser-agent/issues/1, or mute the
> thread
> https://github.com/notifications/unsubscribe/AAAmbo0vS5yKHAT60LvfsyyX7G2FkfHSks5qR7fQgaJpZM4JD3mB
> .

## 

Regards,

ty
